name: Update Registrations

on:
  push:
    branches:
      - main  # Change this to your main branch

jobs:
  update-registrations:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Python script
      run: python .github/workflows/update_registrations.py

    - name: Check for changes
      run: git status

    - name: Stage changed files
      run: git add .

    - name: Commit changed files
      run: git commit -m "Auto updating registrations.txt"

    - name: Fetch from main
      run: git fetch origin main

    - name: Push changes to main
      run: git push origin HEAD:main
